#!/bin/sh
#
# Place applications to be executed when WindowMaker is started here.
# This should only be used for non-X applications or applications that
# do not support session management. Other applications should be restarted
# by the WindowMaker session restoring mechanism. For that, you should
# either set SaveSessionOnExit=YES or select "Save Session" in the Workspace
# submenu of the root menu when all applications you want started are
# running.
#
# WindowMaker will wait until this script finishes, so if you run any
# commands that take long to execute (like a xterm), put a ``&'' in the
# end of the command line.
#
# This file must be executable.
#
xset m 22/10 4

#stop annoying beeps
xset b 0
#check iff conky is running -> kill
if [ -n `pgrep conky` ];then 
	killall conky;
fi
#restart
conky &
##check iff kmixer is running -> kill
#if [ -n `pgrep kmix` ];then 
#	killall kmix;
#fi
##restart
#kmix&
#check iff fbpanel is running -> kill
if [ -n `pgrep lxpanel` ];then 
	killall lxpanel;
fi
#restart
lxpanel &
