#!/bin/sh
#
# Place applications to be executed when WindowMaker is started here.
# This should only be used for non-X applications or applications that
# do not support session management. Other applications should be restarted
# by the WindowMaker session restoring mechanism. For that, you should
# either set SaveSessionOnExit=YES or select "Save Session" in the Workspace
# submenu of the root menu when all applications you want started are
# running.
#
# WindowMaker will wait until this script finishes, so if you run any
# commands that take long to execute (like a xterm), put a ``&'' in the
# end of the command line.
#
# This file must be executable.
#
# mouse acceleration settings
xset m 20/10 10

#stop annoying beeps
xset b 0

# force restart desktop apps, config likely to have changed
killall conky && conky&
killall lxpanel &&lxpanel&

# radiotray is a python app=> does not have "own" pid
ps cax | grep radiotray > /dev/null
if [ $? -ne 0 ]; then
    radiotray&
fi
# tilda could have mulitple instances
if [[ `pidof tilda` -ne 0 ]]; then
    tilda&
fi

# those are smart enough to run only once (ie have demons)
pidgin&
xscreensaver -no-splash &
