#!/bin/bash
#
# Place applications to be executed when WindowMaker is started here.
# This should only be used for non-X applications or applications that
# do not support session management. Other applications should be restarted
# by the WindowMaker session restoring mechanism. For that, you should
# either set SaveSessionOnExit=YES or select "Save Session" in the Workspace
# submenu of the root menu when all applications you want started are
# running.
#
# WindowMaker will wait until this script finishes, so if you run any
# commands that take long to execute (like a xterm), put a ``&'' in the
# end of the command line.
#
# This file must be executable.
#

# start with assumed default layout
sh ~/.screenlayout/extern_right.sh

# mouse acceleration settings
xset m 20/10 10

#stop annoying beeps
xset b 0


# force restart desktop apps, config likely to have changed
ps cax | grep conky > /dev/null
if [[ $? -ne 0 ]]; then
    conky&
fi

ps cax | grep lxpanel > /dev/null
if [[ $? -ne 0 ]]; then
    lxpanel&
fi

# radiotray is a python app=> does not have "own" pid
ps cax | grep radiotray > /dev/null
if [[ $? -ne 0 ]]; then
    radiotray&
fi
# tilda
ps cax | grep tilda > /dev/null
if [[ $? -ne 0 ]]; then
    tilda&
fi

# those are smart enough to run only once (ie have demons)
pidgin&
xscreensaver -no-splash &
